import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from '../components/BlogCard';

const graphcms = new GraphQLClient("https://api-ap-northeast-1.hygraph.com/v2/cl80rmiev0k2y01t90bd1bn00/master")

const QUERY = gql`
  {
    posts {
      id
      title
      subtitle
      slug
      coverPhoto {
        url
      }
      content {
        html
      }
      createdBy {
        name
        picture
      }
    }
  }
`

export async function getStaticProps() {
  const {posts} = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
  };
  
}

export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main className={styles.main}>
        <div className={styles.title_container}>
            <h1>Blogpost Using Graphql</h1>
        </div>
        <div className={styles.card_container}>
        {posts.map((post) => (
          <BlogCard key={post.id} title={post.title} coverPhoto={post.coverPhoto.url} slug={post.slug}/>
        ))}
        </div>
        
      </main>
    </div>
  )
}
